wandb_version: 1

max_new_tokens:
  desc: null
  value: 50
num_beams:
  desc: null
  value: 1
_wandb:
  desc: null
  value:
    python_version: 3.11.9
    cli_version: 0.16.6
    framework: huggingface
    huggingface_version: 4.48.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1747223822.0
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      - 71
      2:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      - 63
      - 71
      3:
      - 13
      - 16
      - 23
      4: 3.11.9
      5: 0.16.6
      6: 4.48.0
      8:
      - 3
      - 5
      13: windows-amd64
