_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.11.9
        t:
            "1":
                - 1
                - 2
                - 3
                - 5
                - 11
                - 41
                - 49
                - 53
                - 55
                - 71
            "2":
                - 1
                - 2
                - 3
                - 5
                - 11
                - 41
                - 49
                - 53
                - 55
                - 63
                - 71
            "3":
                - 13
                - 16
                - 23
                - 24
                - 55
            "4": 3.11.9
            "5": 0.19.9
            "6": 4.52.0.dev0
            "8":
                - 3
                - 5
            "12": 0.19.9
            "13": windows-amd64
max_new_tokens:
    value: 50
num_beams:
    value: 1
